import type { Metadata } from "next"
import NextTopLoader from "nextjs-toploader"
import { Inter } from "next/font/google"
import { Analytics } from "@vercel/analytics/next"
import { Header } from "@/components/Header"
import { Footer } from "@/components/Footer"

import "./globals.css"
import "./dracula.css"
import "./mdx.css"
import { Toaster } from "@/components/ui/sonner"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} antialiased`}>
                <Toaster />
                <NextTopLoader />
                <Header />
                {children}
                <Footer />
                <Analytics />
            </body>
        </html>
    )
}
